package com.example.java_compu.Product;

import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class ProductConfig {

        @Bean
        CommandLineRunner commandLineRunner(ProductRepository repository) {
                return args -> {

                        List<Product> stuff = List.of(

                                        new Product(1L, "NVIDIA GeForce RTX 3080 10GB Graphics Card", "NVIDIA",
                                                        "GPUs / Graphics Cards", 69999, 0,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6429/6429440_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The GeForce RTX 3080 delivers the ultra performance that gamers crave, powered by Ampere—NVIDIA’s 2nd gen RTX architecture. "),
                                        new Product(2L, "NVIDIA GeForce RTX 3060 Ti 8GB Graphics Card", "NVIDIA",
                                                        "GPUs / Graphics Cards", 39999, 10,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6439/6439402_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The GeForce RTX 3060 Ti lets you take on the latest games using the power of Ampere—NVIDIA’s 2nd generation RTX architecture. ."),
                                        new Product(3L, "NVIDIA GeForce RTX 3070 8GB Graphics Card", "NVIDIA",
                                                        "GPUs / Graphics Cards", 49999, 5,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6439/6439402_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The GeForce RTX 3070 is powered by Ampere—NVIDIA’s 2nd gen RTX architecture. Built with enhanced RT Cores and Tensor Cores, ."),
                                        new Product(4L, "NVIDIA GeForce RTX 3090 24GB Graphics Card", "NVIDIA",
                                                        "GPUs / Graphics Cards", 149999, 20,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6429/6429434_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The GeForce RTX 3090 is colossally powerful in every way, giving you a whole new tier of performance. It’s powered byce."),
                                        new Product(5L, "NVIDIA GeForce RTX 3070 Ti 8GB Graphics Card", "NVIDIA",
                                                        "GPUs / Graphics Cards", 59999, 0,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6465/6465789_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The GeForce RTX 3070 Ti is powered by Ampere— NVIDIA’s 2nd gen RTX architecture. Built with enhanced RT Cores and Tensor es."),
                                        new Product(6L, "AMD Radeon RX 6900 XT Graphics", "GIGABYTE",
                                                        "GPUs / Graphics Cards", 99900, 1,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6468/6468934_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The AMD Radeon RX 6900 XT graphics card, powered by AMD RDNA 2 architecture, featuring 80 powerful enhanced Compute Units, 1ming."),
                                        new Product(7L, "AMD Radeon RX 6800 XT Graphics", "XFX",
                                                        "GPUs / Graphics Cards", 64900, 16,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6441/6441226_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The AMD Radeon RX 6800 XT graphics card, powered by AMD RDNA 2 architecture, featuring 72 powerful enhanced Compute Uniting."),
                                        new Product(8L, "AMD Radeon RX 6800 Graphics", "AMD", "GPUs / Graphics Cards",
                                                        57900, 33,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6441/6441226_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The AMD Radeon RX 6800 graphics card, powered by AMD RDNA 2 architecture, featuring 60 powerful enhanced Compute Units,ming."),
                                        new Product(9L, "AMD Radeon RX 6700 XT Graphics", "AMD",
                                                        "GPUs / Graphics Cards", 47900, 21,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6441/6441226_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The AMD Radeon RX 6700 XT graphics card, powered by AMD RDNA 2 architecture, featuring 40 powerful enhanced Compute Uniing."),
                                        new Product(10L, "PNY - XLR8 Gaming Single Fan NVIDIA GeForce GTX 1660 SUPER",
                                                        "PNY", "GPUs / Graphics Cards", 56999, 15,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6407/6407309_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Customize your gaming PC with this PNY GeForce GTX 1660 SUPER gaming graphics card. The 6GB of GDDR5 RAM deliver fast, raceed gameplay."),
                                        new Product(11L, "GIGABYTE - NVIDIA GeForce RTX 3060 12GB", "GIGABYTE",
                                                        "GPUs / Graphics Cards", 47999, 2,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6468/6468925_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Get the ultimate gaming performance with GIGABYTE RTX 3060 Graphics Cards. Powered by NVIDIA's 2nd gen RTX architecture and i Cores."),
                                        new Product(12L, "GIGABYTE - NVIDIA GeForce RTX 3070TI AORUS MASTER 8GB",
                                                        "GIGABYTE", "GPUs / Graphics Cards", 97999, 12,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6467/6467788_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Get the ultimate gaming performance with AORUS RTX 3070 Ti Graphics Cards. Powered by NVIDIA's 2nd gen RTX architectu  Tmory."),
                                        new Product(13L, "ASUS - NVIDIA GeForce GTX 1660 SUPER OC", "ASUS",
                                                        "GPUs / Graphics Cards", 32999, 45,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6405/6405063_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Improve your computer visuals with this Asus TUF Gaming GeForce GTX 1660 SUPER graphics card. The NVIDIA Turing yone."),
                                        new Product(14L, "GIGABYTE - NVIDIA GeForce RTX 3060 12GB", "GIGABYTE",
                                                        "GPUs / Graphics Cards", 159999, 22,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6468/6468928_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Get the ultimate gaming performance with GIGABYTE RTX 3060 Graphics Cards. Powered by NVIDIA's 2nd gen RTX architecture a fores."),
                                        new Product(15L, "ASUS - NVIDIA GeForce RTX 3060 12GB", "ASUS",
                                                        "GPUs / Graphics Cards", 52999, 21,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6460/6460665_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "From top to bottom, the ROG Strix GeForce RTX™ 3060 has been designed to push performance boundaries. A fresh design  scheme"),
                                        new Product(16L, "GIGABYTE - NVIDIA GeForce RTX 3070TI EAGLE 8GB", "GIGABYTE",
                                                        "GPUs / Graphics Cards", 59999, 79,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6467/6467782_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Get the ultimate gaming performance with AORUS RTX 3070 Ti Graphics Cards. Powered by NVIDIA's 2nd gen RTX architeng resmory."),
                                        new Product(17L, "Samsung - 390 Series 24 LED Curved FHD FreeSync Monitor",
                                                        "Samsung", "Monitors", 15999, 18,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5044/5044601_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Enjoy an immersive viewing experience with this Samsung 24-inch curved monitor. An ultra-fast video response prevents bd."),
                                        new Product(18L, "Dell - SE2719HR 27 IPS LED FHD FreeSync Monitor", "Dell",
                                                        "Monitors", 16999, 29,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6394/6394138_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Enjoy crystal-clear HD images on this Dell 27-inch monitor. With a thin-bezel design and built-in power supply, this monitor freesent."),
                                        new Product(19L, "Samsung - T55 Series 27 LED 1000R Curved FHD FreeSync Monitor",
                                                        "Samsung", "Monitors", 23999, 3,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6402/6402202_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "27 Curved Monitor with optimal curvature 1000R"),
                                        new Product(20L, "Dell - S2721HGF 27 Gaming - LED Curved FHD FreeSync and G-SYNC Compatible Monitor",
                                                        "Dell", "Monitors", 23999, 55,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6425/6425903_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "27 Full-HD curved gaming monitor with bold new design. Featuring 144Hz refresh rate and 1ms MPRT for smooth, immersive gameplay."),
                                        new Product(21L, "Samsung - CHG9 Series C49HG90DMN 49 HDR LED Curved FHD FreeSync Monitor",
                                                        "Samsung", "Monitors", 89999, 38,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6115/6115611_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Enhance your gaming experience with this 49-inch Samsung curved gaming monitor. Quantum Dot technology delivers 1 billioay."),
                                        new Product(22L, "LG 34” UltraWide Full HD HDR Monitor with FreeSync", "LG",
                                                        "Monitors", 32999, 0,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6451/6451082_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "LG's premium UltraWide monitors immerse you in everything from content creation to gaming. See a panoramic view made possunencumbered view."),
                                        new Product(23L, "Apple - Pro Display XDR - Nano-Texture Glass", "Apple",
                                                        "Monitors", 599999, 40,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6949/6949006_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Introducing Apple Pro Display XDR. A massive 32 LCD display with Retina 6K resolution and 20.4 million pixels. Gorgenimsold separately."),
                                        new Product(24L, "Apple - Pro Display XDR - Standard Glass", "Apple",
                                                        "Monitors", 499999, 30,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6949/6949006_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Introducing Apple Pro Display XDR. A massive 32 LCD display with Retina 6K resolution and 20.4 million pixels.¹ Gold separately."),
                                        new Product(25L, "LG - 38” UltraWide 21:9 Curved WQHD+ Nano IPS HDR Monitor",
                                                        "LG", "Monitors", 159999, 18,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6419/6419975_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Expansive views to work hard and play harder with a 1ms Nano IPS Display. More than a curved monitor, this is an alway."),
                                        new Product(26L, "LG - UltraGear 34” Nano IPS Curved", "LG", "Monitors", 129999,
                                                        10,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6451/6451084_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Zero In with LG UltraGear™. Getting into that place where it all flows. How you focus, how you play, how you win. LG Ultr new level."),
                                        new Product(27L, "LG - 32 UltraFine IPS LED 4K UHD FreeSync Monitor", "LG",
                                                        "Monitors", 129999, 0,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6314/6314048_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Work on professional creative projects with this 31.5-inch LG UltraFine 4K monitor. Nano IPS and VESA DisplayHDR 600 coarging."),
                                        new Product(28L, "Intel - Core i7-10700K", "Intel", "CPUs / Processors", 34999,
                                                        60,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6411/6411488cv1d.jpg;maxHeight=640;maxWidth=550",
                                                        "Build a powerful PC with this 10th Gen Intel Core i7 desktop processor. The eight cores and Hyper-Threading technoools."),
                                        new Product(29L, "AMD - Ryzen 5 5600X", "AMD", "CPUs / Processors", 27999, 50,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6438/6438943_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Game with the Best 6 incredible cores for those who just want to game. Get the high-speed gaming performance of the cessor."),
                                        new Product(30L, "AMD - Ryzen 7 5800X", "AMD", "CPUs / Processors", 41999, 66,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6439/6439000_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "8 cores optimized for high-FPS gaming rigs. Get the high-speed gaming performance of the world’s best desktop procors."),
                                        new Product(31L, "Intel - Core i9-9900K", "Intel", "CPUs / Processors", 35999,
                                                        28,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6302/6302019cv1d.jpg;maxHeight=640;maxWidth=550",
                                                        "Complete your computer setup with this Intel Core i9 desktop processor. The hyper-threading technology allows for 16-wao data."),
                                        new Product(32L, "Intel - Core i5-10600K", "Intel", "CPUs / Processors", 22999,
                                                        30,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452220_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Set up a powerful desktop PC with this 10th Gen Intel Core i5 processor. DDR4 support and six cores provide acceleraons."),
                                        new Product(33L, "AMD - Ryzen 9 5950X", "AMD", "CPUs / Processors", 74900, 5,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6438/6438941_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "One processor that can game as well as it creates. Get the high-speed gaming performance of the world’s best desktop pror."),
                                        new Product(34L, "CORSAIR - Vengeance RGB PRO 32GB (2x16GB) DDR4", "CORSAIR",
                                                        "RAM / Memory", 15799, 100,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6449/6449223_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR Vengeance RGB PRO Series DDR4 memory lights up your PC with mesmerizing dynamic multi-zone RGB lighting, whhronizeing."),
                                        new Product(35L, "CORSAIR - Vengeance LPX 16GB (2x8GB)", "CORSAIR",
                                                        "RAM / Memory", 7399, 90,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4895/4895506_sa.jpg;maxHeight=640;maxWidth=550",
                                                        "Give your computer a performance boost with this Corsair Vengeance LPX DDR4 DRAM desktop memory, which offers high ng."),
                                        new Product(36L, "CORSAIR - Vengeance RGB PRO SL 32GB (2x16GB)", "CORSAIR",
                                                        "RAM / Memory", 14999, 83,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6457/6457798_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR Vengeance RGB PRO SL DDR4 memory lights up your PC while delivering peak performance in a compact form facn."),
                                        new Product(37L, "PNY - XLR8 16GB (2x8GB)", "PNY", "RAM / Memory", 7999, 78,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6441/6441734cv1d.jpg;maxHeight=640;maxWidth=550",
                                                        "A PNY XLR8 Gaming Chroma RGB Memory Upgrade offers a brilliant RGB design combined with extreme overclocked performanng so."),
                                        new Product(38L, "HyperX FURY HX426C16FB3K2/16 16GB (2x8GB)", "HyperX",
                                                        "RAM / Memory", 8999, 29,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6426/6426290cv1d.jpg;maxHeight=640;maxWidth=550",
                                                        "HyperX FURY DDR4 features an updated heat spreader and speeds up to 3466MHz for a stylish performance boost. FURY DDUs."),
                                        new Product(39L, "HyperX FURY HX432C16FB3AK2/16 16GB (2x8GB)", "HyperX",
                                                        "RAM / Memory", 10399, 44,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6426/6426288cv1d.jpg;maxHeight=640;maxWidth=550",
                                                        "HyperX FURY DDR4 RGB* features RGB lighting and speeds up to 3466MHz** for a stylish performance boost. FURY DDR4 RGB brade."),
                                        new Product(40L, "CORSAIR - Dominator Platinum RGB 64GB (4x16GB)", "CORSAIR",
                                                        "RAM / Memory", 54999, 100,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6337/6337723_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Boost PC performance with this versatile Corsair Dominator Platinum RGB 64GB DDR4 memory kit. Hand-sorted tightly scrds."),
                                        new Product(41L, "HyperX Predator HX432C16PB3AK2/64 64GB (2x32GB)", "HyperX",
                                                        "RAM / Memory", 43699, 60,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6459/6459266_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "HyperX Predator DDR4 RGB pairs brilliant RGB style with dazzling performance. Easily create your look with HyperX's Incities."),
                                        new Product(42L, "PNY - 64GB (4x16GB) 3200MHz DDR4", "PNY", "RAM / Memory",
                                                        29999, 6,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6467/6467033_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "A PNY XLR8 Gaming EPIC-X RGB Memory Upgrade offers a brilliant RGB design combined with extreme overclocked performl."),
                                        new Product(43L, "ASUS - ROG STRIX B550-F", "ASUS", "Motherboards", 17999, 40,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6422/6422283_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "ROG Strix B550 Gaming series motherboards offer a feature-set usually found in the higher-end ROG Strix X570 Gaming CPUs"),
                                        new Product(44L, "MSI - MPG Z490 GAMING EDGE WIFI", "MSI", "Motherboards",
                                                        22999, 30,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6412/6412362_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Set up a high-performance desktop PC with this MSI MPG Z490 Gaming Edge ATX motherboard. The two-way AMD Crossfire gmance."),
                                        new Product(45L, "MSI - MPG X570 GAMING EDGE WIFI", "MSI", "Motherboards",
                                                        19900, 25,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6357/6357223_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Build a powerful PC with this MSI MPG X570 Gaming Edge motherboard. The AM4 socket handles second-generation and thspeeds."),
                                        new Product(46L, "MSI - Z490-A PRO", "MSI", "Motherboards", 17999, 50,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6436/6436464_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "PRO series helps users work smarter by delivering an efficient and productive experience. Featuring stable functioity."),
                                        new Product(47L, "MSI - B550 GAMING PLUS", "MSI", "Motherboards", 14499, 20,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6424/6424047_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The MAG series was born through rigorous quality testing and designed to be a symbol of sturdiness and durability. Focr speedcy."),
                                        new Product(48L, "MSI - Z590 PRO WIFI", "MSI", "Motherboards", 19999, 10,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455367_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The Z590 PRO WIFI ATX motherboard employs a robust VRM platform for the Intel Z590 chipset (LGA 1200, 11th Gen Core r4.0 x16 slot ot)."),
                                        new Product(49L, "ASUS - ROG STRIX Z590-E GAMING WIFI", "ASUS", "Motherboards",
                                                        37999, 22,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452560_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The flagship ROG Strix Z590-E Gaming WiFi motherboard is designed with boosted power delivery and optimized cooling to copeors"),
                                        new Product(50L, "ASUS - ROG MAXIMUS XIII HERO", "ASUS", "Motherboards", 48599,
                                                        11,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452557_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "ROG provides you with the very best gaming-audio inputs and outputs, with special shielded designs, and a collectionponents"),
                                        new Product(51L, "GIGABYTE Z590 AORUS ELITE AX", "GIGABYTE", "Motherboards",
                                                        23999, 49,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454896_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The Z590 AORUS ELITE AX is a great motherboard for mainstream systems, featuring a robust power design and the latest ssors."),
                                        new Product(52L, "MSI - B550 TOMAHAWK", "MSI", "Motherboards", 18999, 87,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6420/6420740_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The MAG series was born through rigorous quality testing and designed to be a symbol of sturdiness and durability. Focused on pratency."),
                                        new Product(53L, "GIGABYTE B550 AORUS PRO", "GIGABYTE", "Motherboards", 20599,
                                                        62,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6420/6420397_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "B550 AORUS PRO AC motherboard uses an 12*+2 phases digital CPU power design which includes both digital PWM Controller ssors."),
                                        new Product(54L, "CORSAIR - RMx Series RM850x 80 PLUS Gold", "CORSAIR",
                                                        "Power Supplies", 14799, 60,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6459/6459244_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR RM850x Series power supplies with EPS12V connectors are built with the highest quality components to deliver 8ar warranty."),
                                        new Product(55L, "EVGA - GP Series SuperNOVA 1000W ATX 80 Plus Gold", "EVGA",
                                                        "Power Supplies", 16999, 45,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6209/6209800_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "The EVGA SuperNOVA G+ Power Supplies have arrived. Launched in 2013, the EVGA SuperNOVA G1 power supplies have been am EVating."),
                                        new Product(56L, "EVGA - W3 Series 450W", "EVGA", "Power Supplies", 2999, 71,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6411/6411819_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Nothing beats a great value, and the EVGA 450 W3 80 PLUS Certified power supply is one of the top-performing budget puild."),
                                        new Product(57L, "CORSAIR - CX-F RGB Series™ CX650F RGB", "CORSAIR",
                                                        "Power Supplies", 9499, 39,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6449/6449963_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR CX-650F RGB Series fully modular power supplies deliver reliable 80 PLUS Bronze efficient power to your syshetic."),
                                        new Product(58L, "CORSAIR - CX-M Series CX750M", "CORSAIR", "Power Supplies",
                                                        8999, 21,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6459/6459241_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR CX-M Series Low-Noise Power Supplies offer 80 PLUS Bronze efficiency and semi-modular cabling for reliable, lowades."),
                                        new Product(59L, "CORSAIR - CX Series Modular CX750M 750W 80 Plus Bronze",
                                                        "CORSAIR", "Power Supplies", 10499, 31,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/8324/8324202_sa.jpg;maxHeight=640;maxWidth=550",
                                                        "This Corsair CX Series Modular CX750M CP-9020061-NA power supply features over- and under-voltage, over-power and shon."),
                                        new Product(60L, "CORSAIR - RMx Series RM1000x 80 PLUS Gold", "CORSAIR",
                                                        "Power Supplies", 18999, 55,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6459/6459246_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR RM1000x Series power supplies with EPS12V connectors are built with the highest quality components to deliver 8ranty."),
                                        new Product(61L, "CORSAIR - CX-F RGB Series CX750F RGB 80 PLUS Bronze",
                                                        "CORSAIR", "Power Supplies", 9999, 51,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6449/6449965_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR CX-750F RGB Series fully modular power supplies deliver reliable 80 PLUS Bronze efficient power to your systemhetic."),
                                        new Product(62L, "CORSAIR - RM Series RM850 850W ATX 80 PLUS GOLD", "CORSAIR",
                                                        "Power Supplies", 13999, 9,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477389_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "CORSAIR RM Series Fully Modular Ultra-Low Noise Power Supplies deliver consistent 80 PLUS Gold efficient power to yourear warranty."),
                                        new Product(63L, "EVGA - GQ Series 850W ATX12V/ EPS12V 80 Plus Gold", "EVGA",
                                                        "Power Supplies", 15999, 0,
                                                        "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5622/5622834_sd.jpg;maxHeight=640;maxWidth=550",
                                                        "Introducing the latest in the EVGA power supply lineup; the GQ series. These power supplies take some of the bert.")

                        );

                        repository.saveAll(stuff);
                };
        }
}